name: CI for Surveilr Tests

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout www.surveilr.com repository
        uses: actions/checkout@v3
        with:
          repository: surveilr/www.surveilr.com
          token: ${{ secrets.GH_PAT }}
          ref: 'main'

      # Step 1: Set up jq
      - name: Install jq
        run: sudo apt-get install -y jq
        
      # Step 1: Set up Deno
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46.3

      # Step 2: Check Deno Version
      - name: Check Deno Version
        run: |
          echo "Checking Deno version..."
          deno --version

          # Step 4: Install or Upgrade Surveilr
      - name: Install or Upgrade Surveilr
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use the token for authentication
        run: |
          set -e
          cd ./lib/assurance/  # Change to the assurance directory
          echo "Checking for Surveilr installation..."
          if command -v surveilr &>/dev/null; then
              echo "Surveilr is installed. Upgrading..."
              ./surveilr upgrade  # Run upgrade
          else
              echo "Surveilr not found. Installing..."
              # Fetch the latest release information
              latest_release=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/opsfolio/surveilr/releases/latest)
              download_url=$(echo "$latest_release" | jq -r '.assets[] | select(.name | contains("tar.gz")) | .browser_download_url')
              
              if [ -z "$download_url" ]; then
                  echo "No downloadable asset found for Surveilr."
                  exit 1
              fi

              curl -L -o surveilr.tar.gz "$download_url"
              tar -xzf surveilr.tar.gz
              chmod +x surveilr  # Make it executable
          fi


      # Step 5: Check Versions
      - name: Check Versions
        run: |
          echo "Checking versions..."
          cd ./lib/assurance/  # Ensure we're in the right directory
          ./surveilr --version  # Check surveilr version

      # Step 6: Run Deno Tests
      - name: Run Deno Tests
        run: |
          echo "Running Deno tests..."
          cd ./lib/assurance/  # Ensure we're in the right directory
          deno test -A --fail-fast
