name: CI for Surveilr Tests

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout www.surveilr.com repository
        uses: actions/checkout@v3
        with:
          repository: surveilr/www.surveilr.com
          token: ${{ secrets.GH_PAT }}
          ref: 'main'

      # Step 1: Set up Deno
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46.3

      # Step 2: Check Deno Version
      - name: Check Deno Version
        run: |
          echo "Checking Deno version..."
          deno --version

      # Step 3: Install eget in ./lib/assurance/
      - name: Install eget
        run: |
          echo "Installing eget..."
          curl -sSL https://zyedidia.github.io/eget.sh | bash
          echo "Moving eget to ./lib/assurance/"
          mv ./eget ./lib/assurance/eget  # Move to ./lib/assurance/
          chmod +x ./lib/assurance/eget  # Make it executable
          echo "eget is located at: ./lib/assurance/eget"

      # Step 4: Install or Upgrade Surveilr
      - name: Install or Upgrade Surveilr
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use the token for authentication
        run: |
          set -e
          cd ./lib/assurance/  # Change to the assurance directory
          echo "Checking for Surveilr installation..."
          if command -v surveilr &>/dev/null; then
              echo "Surveilr is installed. Upgrading..."
              ./eget opsfolio/surveilr --asset tar.gz  # Use the local eget
              ./surveilr upgrade  # Run upgrade
          else
              echo "Surveilr not found. Installing..."
              ./eget opsfolio/surveilr --asset tar.gz  # Use the local eget
          fi

      # Step 5: Check Versions
      - name: Check Versions
        run: |
          echo "Checking versions..."
          cd ./lib/assurance/  # Ensure we're in the right directory
          ./eget --version  # Check eget version
          ./surveilr --version  # Check surveilr version

      # Step 6: Run Deno Tests
      - name: Run Deno Tests
        run: |
          echo "Running Deno tests..."
          cd ./lib/assurance/  # Ensure we're in the right directory
          deno test -A --fail-fast
